### ISSUE TITLE
Trying to clone the Repo to get the CSV results in a 1k file

### ISSUE THREAD

**Issue by libjohn** [metmuseum/openaccess#32]
On behalf of a data patron...

I tried downloading the Repo as a way to get the CSV file.  Can you provide some documentation that clarifies how to do this correctly?

My procedures:

1. go to https://github.com/metmuseum/openaccess
2. Click green button: "Clone or download"
3. Click blue button:  Download ZIP

    - this results in a 6KB zipped file

4. (I'm on Windows):  Extract zipped file (Right-click > Extract All)

    - this results in a 1KB file called MetObjects.csv (plus other minor files.  The largest file is the 7K license)

Please note that I also tried downloading the CSV file, using the download button from the CSV file page:  https://github.com/metmuseum/openaccess/blob/master/MetObjects.csv

[BTW, I'm testing this for a patron who has a low powered mac.  To simulate, I'm using a 4GB RAM Windows VM]

For Microsoft Edge this crashes the browser
For Chrome, it works.  

Can you supply some documentation in the README to clarifies how to download this 268MB file?  I think my patron would appreciate the assistance.  

John Little
Center for Data & Visualization Services
Duke University

**Comment by kallewesterling** [comment]
Hello @libjohn, the GitHub interface can sometimes be a bit misleading. If you click on "Download," it actually opens the whole 268 MB file in the browser. In order to properly _download_ the file, you need to right-click (or if you are using a computer with a trackpad, hold down <kbd>control</kbd> while clicking the link). You should then see a "context-menu" looking something like this:

<img width="1016" alt="Screen Shot 2020-09-18 at 4 10 57 PM" src="https://user-images.githubusercontent.com/7298727/93641159-d2e22480-f9c9-11ea-87ea-76ec79293633.png">

If you then press "Save Link As..." you will be able to save the `.csv` file to whichever folder you want to save it in.

**Comment by kallewesterling** [comment]
@libjohn 

I forgot to add that the file is stored using Git's LFS (large-file storage), which means that if you want to rather clone the repository, you would have to run the following command in your console (Terminal on macOS / Git Bash on Windows):

```console
$ git lfs clone https://github.com/metmuseum/openaccess
```

**Comment by libjohn** [comment]
Super great.  Thanks @kallewesterling

I opened this ticket on behalf of a patron.  It's not for me.  In posting, I was making an assumption (perhaps incorrectly) that this repo will have other casual GitHub users who want the CSV file but don't know the obscure details of how to do an LFS download.   Thought it would be helpful for @metmusum to explain this download procedure in the [README](https://github.com/metmuseum/openaccess/blob/master/README.md).

Take good care.

**Comment by kallewesterling** [comment]
@libjohn Good idea - just opened a pull request with a suggestion based on our discussion.
