### ISSUE TITLE
Missing collections from Provenance Research Project

### ISSUE THREAD

**Issue by andreitr** [metmuseum/openaccess#7]
Any idea why there is no data for "Provenance Research Project" and "Brooklyn Museum Costume Collection"?

**Comment by wandafilardi** [comment]
Hi @andreitr - 

Provenance Research Project and Brooklyn Museum Costume Collection are not listed as departments in the .csv file because they are not curatorial departments. You must have noticed that they are both listed in the departments filter [on the website](https://www.metmuseum.org/art/collection), which was intended to allow quick and easy access to those subsets of objects. 

For reference, all objects associated with The Brooklyn Museum Costume Collection can be found under the department Costume Institute in the csv. The subset of objects that appear when you filter on the site fro Provenance Research Project are from a range of departments, which you can see by further browsing the department filter options on the site.

Hope that helps! 

- Liz
